FROM debian:bullseye

RUN apt update -y

RUN apt install php-fpm php-mysql -y

RUN apt install curl -y

RUN apt install php7.3 -y
RUN apt install php-cli -y
RUN apt install wget -y
RUN apt install php-mysql -y
RUN apt install php-mbstring -y
RUN apt install php-xml -y
RUN apt install sendmail -y
RUN apt install vim

# COPY ./tools/script.sh /
# COPY ./tools/wp-config.php /

# CMD [ "/script.sh" ]
