version: '3.7'

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: ./Users/mikim3/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /Users/mikim3/data/mariadb
                        o: bind
                        type: none

networks:
  inception:
    name: inception

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env
  wordpress:
    depends_on:
      - mariadb
    image: wordpress:latest
    volumes:
      - wordpress:/var/www/html
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env
  nginx:
    image: nginx:latest
    volumes:
      - wordpress:/var/www/html
      # - wordpress:/etc/nginx/conf.d
    ports:
      # - "80:80"
      - "443:443"
    restart: always
