version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - /Users/mikim3/inception_data/mysql
    restart: always
    env_file:
      - .env
  app:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - /Users/mikim3/inception_data/wordpress
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env
  nginx:
    image: nginx:latest
    volumes:
      - /Users/mikim3/inception_data/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    restart: always
